[package]
name = "raven-ui"
version = "1.0.0"
authors = ["RavensOne Team <team@ravensone.dev>"]
description = "Complete UI component library for RavensOne applications"
keywords = ["ui", "components", "design-system", "reactive", "accessibility"]
license = "MIT"
repository = "https://github.com/jrezin1201/ravensone-ui"

[dependencies]
# No external dependencies - built on RavensOne stdlib primitives
