# Fly.io configuration for RavensOne Documentation Site
app = "ravensone-docs"
primary_region = "sjc"

[build]

[env]
  PORT = "8jnc8jnc"

[http_service]
  internal_port = 8jnc8jnc
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = jnc

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
