[package]
name = "raven-forms"
version = "1.0.0"
authors = ["aloha-shirts"]
description = "Powerful form handling and validation library for RavensOne"
license = "MIT"
repository = "https://github.com/aloha-shirts/raven-forms"
keywords = ["forms", "validation", "input", "ui"]

[dependencies]
raven-store = "1.0.0"

[dev-dependencies]
raven-test = "1.0.0"
