[package]
name = "raven-animation"
version = "1.0.0"
authors = ["aloha-shirts"]
description = "Advanced animation library for RavensOne with spring physics, timelines, and gestures"
license = "MIT"
repository = "https://github.com/aloha-shirts/raven-animation"
keywords = ["animation", "transitions", "spring", "physics", "gestures"]

[dependencies]
raven-store = "1.0.0"

[dev-dependencies]
raven-test = "1.0.0"
