[package]
name = "raven-ui"
version = "0.1.0"
authors = ["RavensOne Team <team@ravensone.dev>"]
license = "MIT"
description = "UI component library for RavensOne applications"
repository = "https://github.com/jrezin1201/RavensOne"
homepage = "https://ravensone.dev/docs/packages/raven-ui"
keywords = ["ui", "components", "design-system", "reactive"]

[dependencies]
# raven-signals = "^0.1.0"  # For reactive state (when published)

[dev_dependencies]
# raven-test = "^0.1.0"  # Testing framework (when published)

[build]
target = "wasm32"
optimize = true
ssr = true
hydrate = true

[features]
default = ["button", "input", "card", "modal", "dropdown"]
button = []
input = []
card = []
modal = []
dropdown = []
tabs = []
accordion = []
tooltip = []
badge = []
spinner = []
all = ["button", "input", "card", "modal", "dropdown", "tabs", "accordion", "tooltip", "badge", "spinner"]
